force_cast: error
force_try: error
force_unwrapping: error
type_body_length: 250
file_length: 500
type_name:
  min_length: 2
identifier_name:
  min_length: 2
  max_length: 80
cyclomatic_complexity: 10

disabled_rules:
  - line_length
  - function_body_length
  - weak_delegate
  - trailing_comma
  - class_delegate_protocol

included:
  - Sources
  - Demo
  - Tests
analyzer_rules:
  - unused_import
  - unused_private_declaration